#!/bin/bash
#SBATCH --time 6:00:00 -n 1
#SBATCH --array=1-20
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=36
#SBATCH --output slurm.out
#SBATCH --error slurm.err

R="/work/upbarth/Programs/rosetta"

I=input_flex_c2
O=output_flex_c2

if [ ${SLURM_ARRAY_TASK_ID} -eq 1 ]
then
	D=`date +"%s"`
	mv $O $O.$D
	mkdir $O
else
	sleep 10
fi

S=""
if [ -f $I/span ]; then
	S="-in:file:spanfile $I/span -membrane:Membed_init -membrane::Mhbond_depth -score:weights membrane_highres"
fi

declare -a commands

for i in {1..20}
do
	printf -v si "%02d" $((i-1))
	commands[$i]=""
	for po in "" "_po"; do
		p=""
		if [ -n "$po" ] ; then
			p="-lowres_preoptimize"
		fi
		for j in {1..18};do
			n=$(((i-1)*36+(j-1)))
			printf -v sj "%02d" $((j-1))
			commands[$i]="${commands[$i]}
				$R/source/bin/FlexPepDocking.linuxgccrelease  $S \
				-database $R/database/  \
				-s $I/na${si}_pp.pdb \
				-native $I/native.pdb \
				-pep_refine $p \
				-ex1 -ex2aro -use_input_sc \
				-constant_seed \
				-seed_offset $n \
				-nstruct 10 \
				-out:path:all $O \
				-out:suffix ${po}_$sj \
				> $O/log${po}_${si}_$sj \
				2> $O/err${po}_${si}_$sj &"
		done
	done
	commands[$i]="${commands[$i]}
		wait"
done

bash -c "${commands[${SLURM_ARRAY_TASK_ID}]}"
