#!/bin/bash

R="/work/upbarth/Programs/rosetta"
S=""
if [ -f span ]; then
	S="-in:file:spanfile span -membrane:Membed_init -membrane::Mhbond_depth -score:weights membrane_highres"
fi

$R/source/bin/FlexPepDocking.linuxgccrelease \
	-database $R/database \
	-s $1 \
	-out:pdb \
