#!/bin/bash

printf "#%-7s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %s\n" \
	'I_sc' 'r_sc' 'pep_sc' 'I+pep_sc' 'I_hb' \
	'hb_bb_sc' 'hbond_sc' 'hbond_tot'\
	'Npep' 'Ncontact' 'NctNl' 'Npolar' 'Nnonsat' \
	'ct_pep' 'ctNl_pep' \
	'%tot' '%noloops' '%loops' 'rms' 'I_rms' 'name'

folder="/home/fueglist/Projects/Homology/$1"

folder_base=`basename $folder`
native="$folder/input_loop/native.pdb"
native_tot="$folder/input_loop/native.ct"
native_noloops="$folder/input_loop/native_noloops.ct"
native_loops="$folder/input_loop/native_loops.ct"

contacts -cB $native > $native_tot
contacts -cB ${native_noloops/.ct/.pdb} > $native_noloops
contacts -cB ${native_loops/.ct/.pdb} > $native_loops

Nnative_tot=`cat $native_tot | wc -l`
Nnative_noloops=`cat $native_noloops | wc -l`
Nnative_loops=`cat $native_loops | wc -l`

native_isc=`grep "I_sc " $native | awk '{print $2}'`
native_ihb=`grep "I_hb " $native | awk '{print $2}'`
native_rsc=`grep "reweighted_sc " $native | awk '{print $2}'`
native_psc=`grep "pep_sc " $native | awk '{print $2}'`
native_ipsc=`bc -l <<< $native_isc+$native_psc`

native_rms=`grep "rmsBB " $native | awk '{print $2}'`
native_Irms=`grep "rmsBB_allIF " $native | awk '{print $2}'`

native_pep=`pdb_info -c $native | awk '{print $4}'`
native_polar=`polar -cB $native | wc -l`
native_nonsat=`polar -cB $native \
	| awk '{if ($2 == 0) print $0}' | wc -l`

native_ct_pep=`bc -l <<< $Nnative_tot/$native_pep`
native_ct_noloops_pep=`bc -l <<< $Nnative_noloops/$native_pep`


#l=`grep -v "^$" $native | tail -n $((native_pep+1)) | head -n 2 \
#l=`grep -v "^$" $native | tail -n $((native_pep+1)) | head -n $native_pep \
l=`grep -v "^$" $native | head -n -1 | tail -n 2 \
	| awk '{tot_bb_sc += $11; tot_sc += $12 + $13} END {printf "%8.2f %8.2f %8.2f\n", tot_bb_sc, tot_sc, tot_sc + tot_bb_sc}'`

native_hbond_bb_sc=`echo $l | awk '{print $1}'`
native_hbond_sc=`echo $l | awk '{print $2}'`
native_hbond_tot=`echo $l | awk '{print $3}'`

printf "%8.2f %8.2f %8.2f %8.2f %8d \
%8.2f %8.2f %8.2f \
%8d %8d %8d %8d %8d \
%8.2f %8.2f \
%8.2f %8.2f %8.2f %8.2f %8.2f %s\n" \
	$native_isc $native_rsc $native_psc $native_ipsc $native_ihb \
	$native_hbond_bb_sc $native_hbond_sc $native_hbond_tot \
	$native_pep $Nnative_tot $Nnative_noloops $native_polar $native_nonsat \
	$native_ct_pep $native_ct_noloops_pep \
	"1" "1" "1" $native_rms $native_Irms  "native.pdb" 

#cd /scratch/fueglist/Homology/$folder_base/output_loop/pdbs
#cd /scratch/fueglist/Homology/$folder_base/output_baseline
#cd $folder/input_loop
cd /scratch/fueglist/Homology/$folder_base/output_flex_c2

for p in *.pdb; do
#for p in *_????.pdb; do
#for p in ???.pdb; do
	touch $p
	contacts -cB $p > f_contacts
	remove -r `cat $folder/input_loop/remove_all` $p \
		| contacts -cB > f_contacts_noloops

	isc=`grep "I_sc " $p | awk '{print $2}'`
	ihb=`grep "I_hb " $p | awk '{print $2}'`
	rsc=`grep "reweighted_sc " $p | awk '{print $2}'`
	psc=`grep "pep_sc " $p | awk '{print $2}'`
	ipsc=`bc -l <<< $isc+$psc`

	rms=`grep "rmsBB " $p | awk '{print $2}'`
	Irms=`grep "rmsBB_allIF " $p | awk '{print $2}'`

	Ncts=`cat f_contacts | wc -l`
	Ncts_noloops=`cat f_contacts_noloops | wc -l`
	Ntot=`awk '{print $1}' $native_tot f_contacts | sort | uniq -d | wc -l`
	Nnoloops=`awk '{print $1}' $native_noloops f_contacts_noloops | sort \
		| uniq -d | wc -l`
	Nloops=`awk '{print $1}' $native_loops f_contacts | sort | uniq -d | wc -l`

	tot=0
	noloops=0
	loops=0
	ct_pep=0
	ct_noloops_pep=0
	if (( $Nnative_noloops )); then
		noloops=`bc -l <<< $Nnoloops/$Nnative_noloops`
	fi
	if (( $Nnative_loops )); then
		loops=`bc -l <<< $Nloops/$Nnative_loops`
	fi
	if (( $Nnative_tot )); then
		tot=`bc -l <<< $Ntot/$Nnative_tot`
	fi
	if (( $native_pep )); then
		ct_pep=`bc -l <<< $Ncts/$native_pep`
		ct_noloops_pep=`bc -l <<< $Ncts_noloops/$native_pep`
	fi

	polar=`polar -cB $p | wc -l`
	nonsat=`polar -cB $p | awk '{if ($2 == 0) print $0}' | wc -l`

	#l=`grep -v "^$" $p | tail -n $((native_pep+1)) | head -n 2 \
	#l=`grep -v "^$" $p | tail -n $((native_pep+1)) | head -n $native_pep \
	l=`grep -v "^$" $p | head -n -1 | tail -n 2 \
	| awk '{tot_bb_sc += $11; tot_sc += $12 + $13} END {printf "%8.2f %8.2f %8.2f\n", tot_bb_sc, tot_sc, tot_sc + tot_bb_sc}'`

	hbond_bb_sc=`echo $l | awk '{print $1}'`
	hbond_sc=`echo $l | awk '{print $2}'`
	hbond_tot=`echo $l | awk '{print $3}'`

	printf "%8.2f %8.2f %8.2f %8.2f %8d \
%8.2f %8.2f %8.2f \
%8d %8d %8d %8d %8d \
%8.2f %8.2f \
%8.2f %8.2f %8.2f %8.2f %8.2f %s\n" \
		$isc $rsc $psc $ipsc $ihb \
		$hbond_bb_sc $hbond_sc $hbond_tot \
		$native_pep $Ncts $Ncts_noloops $polar $nonsat \
		$ct_pep $ct_noloops_pep \
		$tot $noloops $loops $rms $Irms $p 
done
rm f_contacts
rm f_contacts_noloops
